name: release

# not on every push. Only then a commit is tagged
on:
  create:
    branches:
      - master
    tags:
      - '*.*.*'


defaults:
  run:
    shell: bash

env:
  PIP_DISABLE_PIP_VERSION_CHECK: 1
  DEST_FOLDER: dist/

permissions:
  contents: read  # This is required for actions/checkout

jobs:
  build:
    if: github.event_name == 'create' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
      with:
        # fetch all branches and tags instead of only fetching the ref/SHA that triggered the workflow
        fetch-depth: 0

    # https://stackoverflow.com/questions/66349002/get-latest-tag-git-describe-tags-when-repo-is-cloned-with-depth-1
    # echo "tag=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_OUTPUT
    - name: Get latest tag
      id: vars
      run: |
        echo "tag=$(git describe --tags)" >> $GITHUB_OUTPUT

    - name: Install py39
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
        cache: pip
        cache-dependency-path: 'requirements/*.pip'

    - name: "Install tools"
      run: |
        python -m pip install --upgrade -r requirements/kit.pip

    - name: build
      env:
        RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
      run: |
        echo "python igor.py build_next $RELEASE_VERSION"
        python igor.py build_next "$RELEASE_VERSION"

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        environment:
          name: pypi
          url: https://pypi.org/p/logging-strict
        permissions:
          id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing

    - name: Release GitHub
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ env.DEST_FOLDER }}*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
